languageCode = "en"
languageName = "English"
weight = 1
title = "l1d1nsec"

[author]
name = "Amine Louzar"
image = "img/author.jpg"
headline = "Cybersecurity Consultant & Auditor | CTO co-founder"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/AmineLz98" },
    { github = "https://github.com/qbecb1zen" },
]